###############################################################################
# Book settings
title       : 'Fire Simulation <br> Lecture Notes'
author      : ''
logo        : 'cce_logo.png'
description : A brief introduction to fire simulations.

###############################################################################
# Exclude settings
exclude_patterns : [.venv/*]

###############################################################################
# Execution settings
execute:
  execute_notebooks : cache

###############################################################################
# TOC settings
only_build_toc_files : true
number_toc_chapters  : true

###############################################################################
# HTML-specific settings
html:
  favicon               : 'cce_logo_standalone_icon.png'
  home_page_in_navbar   : true
  baseurl               : 'https://firedynamics.github.io/LectureFireSimulation'
  use_edit_page_button  : true
  use_edit_page_button  : true
  use_issues_button     : true
  use_repository_button : true
  extra_footer          : |
    <p>
    <img src='https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-sa.svg' height='31'/>
    | By Team Fire | Contacts and Infos: <a href='https://cce.uni-wuppertal.de/en.html'>CCE@BUW</a> and <a href='https://www.fz-juelich.de/ias/ias-7/EN/Research/Fire_Dynamics/_node.html'>IAS-7@FZJ</a>
    </br>Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
    </p>
  extra_navbar          : ''
  
###############################################################################
# Interact link settings
notebook_interface : "notebook"

###############################################################################
# Sphinx settings
sphinx:
  config:
#     bibtex_reference_style: "author_year"
    html_show_copyright : false
    mathjax3_config     :
      tex:
        macros:
          "vv": "\\vec{v}"
          "vu": "\\vec{u}"
          "mf": "\\small\\sf"
          "dQ": "\\dot{Q}"
          "dq": "\\dot{q}"
          "dm": "\\dot{m}"
          "du": "\\dot{u}"

###############################################################################
# parser settings
# parse:
#   myst_extended_syntax: true
#   myst_enable_extensions:
#     - amsmath
#     - colon_fence
#     - deflist
#     - dollarmath
#     - html_admonition
#     - html_image
#     - linkify
#     - replacements
#     - smartquotes
#     - substitution
#     - jupyterbook_latex

###############################################################################
# BibTeX settings
bibtex_reference_style : author_year
bibtex_bibfiles        :
    - content/references.bib

###############################################################################
# Launch button settings
repository:
  url            : "https://github.com/FireDynamics/LectureFireSimulation"
  branch         : main
  path_to_book   : "book"

launch_buttons:
  jupyterhub_url : https://io.cce.uni-wuppertal.de/firesim_ss21/

#binder:
#  binderhub_url               : "https://mybinder.org"
#  text                        : "Launch binder"

#latex:
#  latex_engine                : "xelatex"
#  latex_documents:
#    targetname: book.tex
