###############################################################################
# Book settings
title       : Fire Simulation Lecture
author      : Team Fire | CCE@BUW + IAS-7@FZJ
logo        : 'cce_logo.png'
description : A brief introduction to fire simulations.

###############################################################################
# Exclude settings
exclude_patterns : [.venv/*]

###############################################################################
# Execution settings
execute:
  execute_notebooks : cache

###############################################################################
# TOC settings
only_build_toc_files : true
number_toc_chapters  : true

###############################################################################
# HTML-specific settings
html:
  favicon               : 'cce_logo_standalone_icon.png'
  home_page_in_navbar   : true
  baseurl               : 'https://firedynamics.github.io/LectureFireSimulation/content/overview/01_overview.html'
  use_edit_page_button  : true
  use_edit_page_button  : true
  use_issues_button     : true
  use_repository_button : true
  
###############################################################################
# Interact link settings
notebook_interface : "notebook"

###############################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright : false
    
###############################################################################
# BibTeX settings
bibtex_reference_style : author_year
bibtex_bibfiles        :
    - content/references.bib

###############################################################################
# Launch button settings
repository:
  url            : "https://github.com/FireDynamics/LectureFireSimulation"
  branch         : main
  path_to_book   : "book"

launch_buttons:
  jupyterhub_url : https://io.cce.uni-wuppertal.de/firesim_ss2020/

#binder:
#  binderhub_url               : "https://mybinder.org"
#  text                        : "Launch binder"

#latex:
#  latex_engine                : "xelatex"
#  latex_documents:
#    targetname: book.tex
